#!/bin/sh
# webshield CLI installer: detects OS/architecture, downloads the release archive,
# verifies the checksum and puts the binary into ~/.local/bin.
#
#   curl -fsSL <url>/install.sh | sh              # latest version
#   curl -fsSL <url>/install.sh | sh -s -- 0.1.0  # specific version
#
# Environment variables:
#   WEBSHIELD_CLI_VERSION  — version (or first argument; empty = latest release)
#   WEBSHIELD_CLI_BASE_URL — release base URL (defaults to the repo's GitHub releases)
#   WEBSHIELD_CLI_BINDIR   — install directory (defaults to ~/.local/bin)
#   WEBSHIELD_CLI_NO_COMPLETION — set to 1 to skip installing the shell completion
set -eu

REPO="webshieldpro/webshield-cli"
BASE="${WEBSHIELD_CLI_BASE_URL:-https://github.com/$REPO/releases/download}"
VERSION="${WEBSHIELD_CLI_VERSION:-${1:-}}"
BINDIR="${WEBSHIELD_CLI_BINDIR:-$HOME/.local/bin}"

# Without an explicit version, take the latest release tag from the GitHub API.
if [ -z "$VERSION" ]; then
  VERSION="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
    | sed -n 's/.*"tag_name": *"v\{0,1\}\([^"]*\)".*/\1/p' | head -1)"
  if [ -z "$VERSION" ]; then
    echo "failed to determine the latest version; set WEBSHIELD_CLI_VERSION=X.Y.Z" >&2
    exit 1
  fi
fi
TAG="v$VERSION"

os="$(uname -s)"; arch="$(uname -m)"
case "$os" in
  Linux)  plat="unknown-linux-musl" ;;
  Darwin) plat="apple-darwin" ;;
  *) echo "unsupported OS: $os" >&2; exit 1 ;;
esac
case "$arch" in
  x86_64|amd64)  cpu="x86_64" ;;
  aarch64|arm64) cpu="aarch64" ;;
  *) echo "unsupported architecture: $arch" >&2; exit 1 ;;
esac

target="$cpu-$plat"
asset="webshield-$VERSION-$target.tar.gz"
url="$BASE/$TAG/$asset"

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
echo "Downloading $url"
curl -fSL "$url" -o "$tmp/$asset"

# Verify the checksum when SHA256SUMS is available.
if curl -fsSL "$BASE/$TAG/SHA256SUMS" -o "$tmp/SHA256SUMS" 2>/dev/null; then
  ( cd "$tmp" && grep " ./$asset\$\| $asset\$" SHA256SUMS | sed "s| \./| |" | sha256sum -c - ) \
    || { echo "checksum mismatch" >&2; exit 1; }
fi

tar -xzf "$tmp/$asset" -C "$tmp"
mkdir -p "$BINDIR"
install -m 0755 "$tmp/webshield" "$BINDIR/webshield"
echo "Installed: $BINDIR/webshield ($($BINDIR/webshield --version))"
case ":$PATH:" in
  *":$BINDIR:"*) ;;
  *) echo "Add to PATH: export PATH=\"$BINDIR:\$PATH\"" ;;
esac

# Install a completion script for the caller's login shell. Best-effort: it must
# never abort the installation (the binary is already in place). The script is
# generated by the freshly installed binary, so it always matches this version.
# Target directory depends on privileges: root writes to the system-wide dir,
# an unprivileged user to a per-user dir under $HOME.
install_completion() {
  [ "${WEBSHIELD_CLI_NO_COMPLETION:-0}" = 1 ] && return 0

  bin="$BINDIR/webshield"
  shell_name="$(basename "${SHELL:-}")"
  is_root=0; [ "$(id -u 2>/dev/null || echo 1000)" = 0 ] && is_root=1

  case "$shell_name" in
    bash)
      if [ "$is_root" = 1 ]; then
        dir="/usr/share/bash-completion/completions"
      else
        dir="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions"
      fi
      file="$dir/webshield" ;;
    zsh)
      if [ "$is_root" = 1 ]; then
        dir="/usr/local/share/zsh/site-functions"
        [ -d /usr/share/zsh/site-functions ] && dir="/usr/share/zsh/site-functions"
      else
        dir="$HOME/.zsh/completions"
      fi
      file="$dir/_webshield" ;;
    fish)
      if [ "$is_root" = 1 ]; then
        dir="/usr/share/fish/vendor_completions.d"
      else
        dir="${XDG_CONFIG_HOME:-$HOME/.config}/fish/completions"
      fi
      file="$dir/webshield.fish" ;;
    nu)
      # Nushell has no autoload dir; the file must be sourced explicitly.
      shell_name="nushell"
      dir="${XDG_CONFIG_HOME:-$HOME/.config}/nushell/completions"
      file="$dir/webshield.nu" ;;
    *)
      # Unknown or unset login shell — nothing to wire up automatically.
      echo "Shell completion: run '$bin completion <bash|zsh|fish|powershell|elvish|nushell>' to generate it."
      return 0 ;;
  esac

  mkdir -p "$dir" 2>/dev/null || { echo "Shell completion: cannot write to $dir (skipped)"; return 0; }
  if "$bin" completion "$shell_name" > "$file" 2>/dev/null; then
    echo "Installed shell completion: $file"
    # zsh loads completions from $fpath only; the per-user dir usually is not in it.
    if [ "$shell_name" = zsh ] && [ "$is_root" != 1 ]; then
      echo "  For zsh, add to ~/.zshrc before 'compinit': fpath=(\"$dir\" \$fpath)"
    fi
    # Nushell autoloads nothing; the script has to be sourced from the config.
    if [ "$shell_name" = nushell ]; then
      echo "  For Nushell, add to your config.nu: source \"$file\""
    fi
  else
    rm -f "$file" 2>/dev/null || true
    echo "Shell completion: generation failed (skipped)"
  fi
  return 0
}
install_completion
